const bridge=window.NodScoreBridge,layout=document.getElementById('scoreLayout'),main=layout.querySelector('canvas');
const controls=document.createElement('div');controls.className='auto-scroll-controls';controls.innerHTML='<label>BPM <input id="scrollBpm" type="number" min="30" max="240" value="80"></label><label>每行小節 <input id="scrollBars" type="number" min="1" max="16" value="4"></label><label>放大 <select id="scoreZoom"><option value="100">100%</option><option value="105">105%</option><option value="110">110%</option><option value="115">115%</option><option value="120">120%</option><option value="130">130%</option><option value="140">140%</option><option value="150">150%</option></select></label><button id="scrollToggle">開始捲譜</button><button id="scrollReset">回到頁首</button>';
document.body.append(controls);const css=document.createElement('style');css.textContent='.auto-scroll-controls{position:fixed;left:8px;bottom:calc(44px + env(safe-area-inset-bottom));z-index:25;display:flex;align-items:center;gap:6px;flex-wrap:wrap;padding:6px 8px;border-radius:12px;background:#ffffffed;color:#183c2b;border:1px solid #a7c9b8;font-size:13px}.auto-scroll-controls input{width:60px;padding:5px;background:white;color:#183c2b}.auto-scroll-controls button{padding:6px 9px;font-size:13px}.page-fit.auto-scrolling #scoreLayout{position:absolute!important;inset:env(safe-area-inset-top) 0 auto!important;height:auto!important;display:block!important;will-change:transform}.page-fit.auto-scrolling #scoreLayout canvas{display:block;width:100%!important;height:auto!important;max-height:none!important;object-fit:initial}.page-fit.score-zoom #scoreLayout{width:var(--score-zoom-width)!important;margin-left:var(--score-zoom-margin)!important}.auto-scroll-controls select{padding:5px;background:white;color:#183c2b}.scroll-preview{margin-top:18px}.dark-score .auto-scroll-controls{background:#142b20;color:#d9f5e5}@media print{.auto-scroll-controls,.scroll-preview{display:none!important}}';document.head.append(css);
const $=id=>document.getElementById(id);let running=false,offset=0,last=0,key='',preview=null,request=0;
let zoom=100;function setZoom(value){const old=zoom;zoom=Math.max(100,Math.min(150,Number(value)||100));offset*=zoom/old;const surface=document.getElementById('readingSurface');surface.classList.add('score-zoom');surface.style.setProperty('--score-zoom-width',zoom+'%');surface.style.setProperty('--score-zoom-margin',(100-zoom)/2+'%');try{localStorage.setItem('score-reading-zoom',zoom);}catch{}}try{$('scoreZoom').value=localStorage.getItem('score-reading-zoom')||'100';}catch{}setZoom($('scoreZoom').value);$('scoreZoom').onchange=()=>{setZoom($('scoreZoom').value);bridge.wholePage();};
function stop(){running=false;$('scrollToggle').textContent='繼續捲譜';}
function reset(){offset=0;layout.style.transform='';}
function contextKey(){const c=bridge.context();return c.songId+':'+c.pageIndex;}
async function prepare(){const token=++request;preview?.remove();preview=null;const data=bridge.scrollData();if(!data?.next)return;const p=data.next,im=new Image();im.src=p.image;try{await im.decode();}catch{return;}if(token!==request)return;const full=document.createElement('canvas');full.width=p.width;full.height=p.height;const ctx=full.getContext('2d');ctx.drawImage(im,0,0,p.width,p.height);
for(const m of p.marks||[]){ctx.fillStyle=m.bg;ctx.fillRect(m.maskX??m.x-m.w/2,m.y-24,m.maskWidth??m.w,24+(m.maskBottom??20));}
for(const m of p.marks||[]){const [n,color]=data.styles[m.chord];ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold '+(m.numberSize||27)+'px Arial';ctx.fillText(n,m.x,m.y-12);const size=m.chordSize||16,parts=/^([A-G])(.+)?$/.exec(m.chord);ctx.textBaseline='top';ctx.font='bold '+size+'px Arial';if(parts?.[2]){const rw=ctx.measureText(parts[1]).width;ctx.font='bold '+size*.7+'px Arial';const sw=ctx.measureText(parts[2]).width,left=m.x-(rw+sw)/2;ctx.textAlign='left';ctx.font='bold '+size+'px Arial';ctx.fillText(parts[1],left,m.y+3);ctx.font='bold '+size*.7+'px Arial';ctx.fillText(parts[2],left+rw,m.y+3+size*.35);}else ctx.fillText(m.chord,m.x,m.y+3);for(const a of m.lyrics||[]){ctx.beginPath();ctx.roundRect(a.x-(a.width||42)/2,a.y-(a.height||42)/2,a.width||42,a.height||42,8);ctx.strokeStyle=color;ctx.lineWidth=3;ctx.stroke();}}
const crop=data.crop||{x:0,y:0,w:p.width,h:p.height};preview=document.createElement('canvas');preview.className='scroll-preview';preview.width=crop.w;preview.height=crop.h;preview.getContext('2d').drawImage(full,crop.x,crop.y,crop.w,crop.h,0,0,crop.w,crop.h);
if(document.body.classList.contains('dark-score')){const pc=preview.getContext('2d'),image=pc.getImageData(0,0,preview.width,preview.height);for(let i=0;i<image.data.length;i+=4){const d=image.data,r=d[i],g=d[i+1],b=d[i+2];if(Math.max(r,g,b)-Math.min(r,g,b)>25)continue;const gray=Math.round(.299*r+.587*g+.114*b),v=gray>=210?0:255-gray;d[i]=d[i+1]=d[i+2]=v;}pc.putImageData(image,0,0);}
layout.append(preview);}
$('scrollToggle').onclick=()=>{if(running){stop();return;}bridge.wholePage();document.getElementById('readingSurface').classList.add('auto-scrolling');running=true;last=0;key=contextKey();prepare();$('scrollToggle').textContent='暫停捲譜';};
$('scrollReset').onclick=()=>{reset();};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
function tick(t){const c=bridge.context();controls.hidden=c.tab!=='score'||c.correcting;
if(c.tab!=='score'||c.correcting||!c.pageFit){if(running)stop();document.getElementById('readingSurface').classList.remove('auto-scrolling');reset();preview?.remove();preview=null;}
if(contextKey()!==key){key=contextKey();reset();if(running){bridge.wholePage();prepare();}}
if(running){const dt=last?Math.min((t-last)/1000,.1):0,data=bridge.scrollData(),height=main.getBoundingClientRect().height,bpm=Math.max(30,Math.min(240,Number($('scrollBpm').value)||80)),bars=Math.max(1,Math.min(16,Number($('scrollBars').value)||4)),beats=data.beats||4,rows=data.rows||6;
offset+=dt*height/rows*bpm/(60*bars*beats);layout.style.transform='translateY(-'+offset+'px)';
if(offset>=height+18&&data.next){const remainder=offset-height-18,readyPreview=preview;bridge.turn(1);if(readyPreview){main.width=readyPreview.width;main.height=readyPreview.height;main.getContext('2d').drawImage(readyPreview,0,0);}key=contextKey();offset=remainder;layout.style.transform='translateY(-'+offset+'px)';prepare();}else if(!data.next&&offset>=Math.max(0,height-innerHeight*.45)){stop();}}
last=t;requestAnimationFrame(tick);}
requestAnimationFrame(tick);
