import {CameraService} from '../../experiments/eye-blink-poc/js/camera-service.mjs?v=6';
import {NodController} from '../../experiments/eye-blink-poc/js/nod-controller.mjs?v=8';
const bridge=window.NodScoreBridge;if(!bridge)throw Error('歌譜點頭介面未就緒');
const css=document.createElement('link');css.rel='stylesheet';css.href='./nod-score.css?v=4';document.head.append(css);
const panel=document.createElement('details');panel.className='score-nod-panel';panel.id='scoreNodPanel';panel.innerHTML='<summary>點頭翻頁（實驗）</summary><div class="score-nod-buttons"><button id="scoreNodStart">啟動點頭</button><button id="scoreNodCalibrate" disabled>校準點頭</button><button id="scoreNodStop" disabled>關閉攝影機</button></div><p>校準時只要正常看著螢幕中央兩秒，不用先點頭。往下點、回原位算一次；三次下頁，兩次上頁。</p><label>連續動作間隔 <input id="scoreNodInterval" type="range" min="400" max="4000" step="100" value="2000"> <output id="scoreNodSeconds">2.0</output> 秒</label><p id="scoreNodAngles">等待頭部角度資料</p><label>點頭幅度 <input id="scoreNodSensitivity" type="range" min="6" max="20" value="8"><output id="scoreNodDegrees">8</output>°</label><p id="scoreNodStatus" role="status">尚未啟動；只控制目前歌曲的頁面。</p>';
document.querySelector('.toolbar').append(panel);
const hud=document.createElement('div');hud.className='score-nod-hud';hud.hidden=true;hud.id='scoreNodHud';hud.innerHTML='<video id="scoreNodVideo" autoplay muted playsinline aria-label="點頭辨識本機預覽"></video><div><strong id="scoreNodCount">0</strong><small id="scoreNodState">準備中</small></div><button id="scoreNodQuickStop" aria-label="關閉點頭攝影機">×</button>';document.body.append(hud);
const $=id=>document.getElementById(id);let active=false,loading=false,lastSong=null,heldNumber=0,heldUntil=0,message='尚未啟動';
const guide=document.createElement('section');guide.id='scoreNodGuide';guide.className='score-nod-guide';guide.hidden=true;guide.innerHTML='<div class="nod-guide-card"><small id="scoreNodGuideStep">點頭操作提示</small><h2 id="scoreNodGuideTitle"></h2><p id="scoreNodGuideText"></p><div id="scoreNodGuideNumber">0</div><div class="nod-guide-actions"><button id="scoreNodGuideStart">重新啟動攝影機</button><button id="scoreNodGuideCalibrate">開始校準</button><button id="scoreNodGuidePlay">開始看譜</button><button id="scoreNodGuideMore">展開提示</button><button id="scoreNodGuideStop">關閉點頭</button></div></div>';document.body.append(guide);let guideExpanded=true,guideRequested=false,guideDetail='',actionMessage='已翻頁';
function receipt(number,t){heldNumber=number;heldUntil=t+1600;$('scoreNodCount').textContent=number;}
const nod=new NodController(event=>{const result=bridge.turn(event.gesture==='NEXT_PAGE'?1:-1);receipt(event.blinkCount,event.timestamp);message=result.turned?(event.gesture==='NEXT_PAGE'?'已到下一頁':'已到上一頁'):'已到本曲頁面邊界';actionMessage=message;$('scoreNodStatus').textContent=message;},{simpleCalibration:true});
const camera=new CameraService($('scoreNodVideo'),frame=>{const context=bridge.context();if(context.tab!=='score'||context.correcting){nod.loseFace('選歌中，暫停翻頁；攝影機持續開啟');nod.lastInput=frame.t;heldNumber=0;return;}if(context.songId!==lastSong){lastSong=context.songId;nod.loseFace('切換歌曲，取消上一組動作');}const wasCalibrating=!!nod.calibration;const before=nod.count;nod.feed(frame.t,frame.head,frame.face);if(wasCalibrating&&!nod.calibration&&nod.baseline!==null)nod.threshold=Number($('scoreNodSensitivity').value);if(nod.count>before)receipt(nod.count,frame.t);saveProfile();message=nod.calibration||nod.baseline===null?nod.message:nod.cancelReason||'校準完成；三次下頁，兩次上頁';$('scoreNodStatus').textContent=message;},(status,detail)=>{guideDetail=detail;active=camera?.running??false;if(status==='CAMERA READY'&&nod.baseline===null)nod.reset();loading=status==='MODEL LOADING';$('scoreNodStart').disabled=active||loading;$('scoreNodCalibrate').disabled=!active;$('scoreNodStop').disabled=!(active||loading);hud.hidden=!(active||loading);if(!active)nod.loseFace();$('scoreNodStatus').textContent=detail;});
async function start(){const context=bridge.context();if(context.tab!=='score'||!context.pageCount||context.correcting){$('scoreNodStatus').textContent='請先開啟一首歌曲，並關閉標記校正';return;}guideExpanded=true;guideRequested=true;lastSong=context.songId;nod.reset();nod.interval=Number($('scoreNodInterval').value);let stored=null;try{stored=JSON.parse(localStorage.getItem(profileKey)||'null');}catch{}if(nod.restoreProfile(stored)){guideExpanded=false;$('scoreNodInterval').value=nod.interval;$('scoreNodSeconds').textContent=(nod.interval/1000).toFixed(1);$('scoreNodSensitivity').value=nod.threshold;$('scoreNodDegrees').textContent=nod.threshold;}heldNumber=0;$('scoreNodCount').textContent='0';await camera.start({width:320,targetFps:24,delegate:'CPU'});}
function stop(reason='點頭攝影機已關閉'){camera.stop(reason);nod.reset();active=loading=false;hud.hidden=true;guide.hidden=true;guideRequested=false;}
$('scoreNodStart').onclick=start;$('scoreNodStop').onclick=()=>stop();$('scoreNodQuickStop').onclick=()=>stop();$('scoreNodCalibrate').onclick=()=>{guideExpanded=true;nod.startCalibration(performance.now());heldNumber=0;$('scoreNodStatus').textContent=nod.message;};
$('scoreNodInterval').oninput=()=>{const ms=Number($('scoreNodInterval').value);nod.setInterval(ms);$('scoreNodSeconds').textContent=(ms/1000).toFixed(1);saveProfile();heldNumber=0;heldUntil=0;$('scoreNodStatus').textContent='間隔已套用，上一組未完成動作已取消';};
const timer=setInterval(()=>{updateGuide();const context=bridge.context();if((active||loading)&&(context.tab!=='score'||context.correcting)){$('scoreNodState').textContent='選歌時暫停';return;}if(!active)return;if(context.songId!==lastSong){lastSong=context.songId;nod.loseFace('切換歌曲，取消上一組動作');}nod.tick(performance.now());const metrics=camera.stats();$('scoreNodAngles').textContent='相對角度 '+(nod.relative??0).toFixed(1)+'° · 實際辨識 '+metrics.inferenceFps.toFixed(1)+' FPS';$('scoreNodCount').textContent=performance.now()<=heldUntil?heldNumber:nod.count;$('scoreNodState').textContent=nod.calibration?'校準中':nod.phase==='READY'?'可點頭':nod.phase==='DOWN'?'請回原位':nod.phase==='COOLDOWN'?'已翻頁':nod.baseline===null?'請校準':'等待回原位';if(nod.cancelReason)$('scoreNodStatus').textContent=nod.cancelReason;},100);
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop('進入背景，攝影機已關閉；返回後請啟動攝影機，沿用已儲存校準');});window.addEventListener('pagehide',()=>{stop();});

$('scoreNodSensitivity').oninput=()=>{nod.threshold=Number($('scoreNodSensitivity').value);$('scoreNodDegrees').textContent=nod.threshold;nod.loseFace('幅度已調整，請回到原位再點頭');saveProfile();};
function updateGuide(){
  guide.hidden=!(active||loading||guideRequested)||bridge.context().tab!=='score';if(guide.hidden)return;guide.classList.toggle('compact',!guideExpanded);
  let title,text,step;const cal=!!nod.calibration,ready=nod.baseline!==null&&!cal;
  if(!active&&!loading){step='第 1 步 · 攝影機尚未啟動';title='請重新啟動攝影機';text=guideDetail;}else if(loading){step='第 1 步 · 啟動攝影機';title='請允許使用前鏡頭';text='按 Safari 的「允許」，等待載入。這時不用點頭。';}
  else if(cal){step='第 2 步 · 校準姿勢';title=nod.message;text='正常看著螢幕中央，保持原本姿勢；不要點頭，也不用盯著鏡頭。';}
  else if(!ready){step='第 2 步 · 準備校準';title=nod.cancelReason?'校準尚未完成':'看著螢幕中央，準備好了按開始校準';text=nod.cancelReason?nod.message:'坐在平常彈奏的位置，頭保持自然姿勢，按下方「開始校準」。';}
  else{step='校準完成 · 可點頭翻頁';
    if(nod.phase==='DOWN'){title='請把頭抬回原本看譜的姿勢';text='往下點、再抬回來，才算一次完整點頭。';}
    else if(nod.phase==='COOLDOWN'){title=actionMessage;text='這一組動作已收到。回到原本姿勢，再開始下一組。';}
    else if(nod.count===2){title='收到 2 次：再點一次下頁；停下來上頁';text='想往下頁，再向下點並抬回一次。想往上頁，就保持正常姿勢等待。';}
    else if(nod.count===1){title='收到 1 次，請再點頭並抬回';text='每次往下點後都要回到原本姿勢。';}
    else if(nod.phase==='WAIT_FOR_CENTER'){title='請回到原本看螢幕中央的姿勢';text=nod.cancelReason||'回到原位後，才能開始下一組點頭。';}
    else{title='正常點頭 3 次下頁；2 次上頁';text='往下點、抬回算 1 次。可以先做三次練習，或按「開始看譜」。';}
  }
  $('scoreNodGuideStep').textContent=step;$('scoreNodGuideTitle').textContent=title;$('scoreNodGuideText').textContent=text;
  $('scoreNodGuideNumber').textContent=cal?Math.max(0,Math.ceil((2000-performance.now()+nod.calibration.started)/1000)):performance.now()<=heldUntil?heldNumber:nod.count;
  $('scoreNodGuideStart').hidden=active||loading;$('scoreNodGuideCalibrate').textContent=ready?'重新校準':'開始校準';$('scoreNodGuideCalibrate').hidden=!active||loading||cal;$('scoreNodGuidePlay').hidden=!ready||!guideExpanded;$('scoreNodGuideMore').hidden=guideExpanded;
}
$('scoreNodGuideCalibrate').onclick=()=>$('scoreNodCalibrate').click();$('scoreNodGuidePlay').onclick=()=>{guideExpanded=false;bridge.wholePage?.();updateGuide();};$('scoreNodGuideMore').onclick=()=>{guideExpanded=true;updateGuide();};$('scoreNodGuideStop').onclick=()=>stop();

$('scoreNodGuideStart').onclick=start;

const profileKey='smart-guitar-score-nod-calibration-v1';let savedProfileText='';function saveProfile(){const p=nod.profile();if(!p)return;const text=JSON.stringify(p);if(text===savedProfileText)return;try{localStorage.setItem(profileKey,text);savedProfileText=text;}catch{$('scoreNodStatus').textContent='目前瀏覽器無法儲存校準；本次仍可使用';}}
