import {CameraService} from '../../experiments/eye-blink-poc/js/camera-service.mjs?v=6';
import {NodController} from '../../experiments/eye-blink-poc/js/nod-controller.mjs?v=7';
const bridge=window.NodScoreBridge;if(!bridge)throw Error('歌譜點頭介面未就緒');
const css=document.createElement('link');css.rel='stylesheet';css.href='./nod-score.css?v=2';document.head.append(css);
const panel=document.createElement('details');panel.className='score-nod-panel';panel.id='scoreNodPanel';panel.innerHTML='<summary>點頭翻頁（實驗）</summary><div class="score-nod-buttons"><button id="scoreNodStart">啟動點頭</button><button id="scoreNodCalibrate" disabled>校準點頭</button><button id="scoreNodStop" disabled>關閉攝影機</button></div><p>校準時只要正常看著螢幕中央兩秒，不用先點頭。往下點、回原位算一次；三次下頁，兩次上頁。</p><label>連續動作間隔 <input id="scoreNodInterval" type="range" min="400" max="4000" step="100" value="2000"> <output id="scoreNodSeconds">2.0</output> 秒</label><p id="scoreNodAngles">等待頭部角度資料</p><label>點頭幅度 <input id="scoreNodSensitivity" type="range" min="6" max="20" value="8"><output id="scoreNodDegrees">8</output>°</label><p id="scoreNodStatus" role="status">尚未啟動；只控制目前歌曲的頁面。</p>';
document.querySelector('.toolbar').append(panel);
const hud=document.createElement('div');hud.className='score-nod-hud';hud.hidden=true;hud.id='scoreNodHud';hud.innerHTML='<video id="scoreNodVideo" autoplay muted playsinline aria-label="點頭辨識本機預覽"></video><div><strong id="scoreNodCount">0</strong><small id="scoreNodState">準備中</small></div><button id="scoreNodQuickStop" aria-label="關閉點頭攝影機">×</button>';document.body.append(hud);
const $=id=>document.getElementById(id);let active=false,loading=false,lastSong=null,heldNumber=0,heldUntil=0,message='尚未啟動';
function receipt(number,t){heldNumber=number;heldUntil=t+1600;$('scoreNodCount').textContent=number;}
const nod=new NodController(event=>{const result=bridge.turn(event.gesture==='NEXT_PAGE'?1:-1);receipt(event.blinkCount,event.timestamp);message=result.turned?(event.gesture==='NEXT_PAGE'?'已到下一頁':'已到上一頁'):'已到本曲頁面邊界';$('scoreNodStatus').textContent=message;},{simpleCalibration:true});
const camera=new CameraService($('scoreNodVideo'),frame=>{const context=bridge.context();if(context.tab!=='score'||context.correcting){stop('離開樂譜或進入校正，已關閉攝影機');return;}if(context.songId!==lastSong){lastSong=context.songId;nod.loseFace('切換歌曲，取消上一組動作');}const wasCalibrating=!!nod.calibration;const before=nod.count;nod.feed(frame.t,frame.head,frame.face);if(wasCalibrating&&!nod.calibration&&nod.baseline!==null)nod.threshold=Number($('scoreNodSensitivity').value);if(nod.count>before)receipt(nod.count,frame.t);message=nod.calibration||nod.baseline===null?nod.message:nod.cancelReason||'校準完成；三次下頁，兩次上頁';$('scoreNodStatus').textContent=message;},(status,detail)=>{active=camera?.running??false;loading=status==='MODEL LOADING';$('scoreNodStart').disabled=active||loading;$('scoreNodCalibrate').disabled=!active;$('scoreNodStop').disabled=!(active||loading);hud.hidden=!(active||loading);if(!active)nod.loseFace();$('scoreNodStatus').textContent=detail;});
async function start(){const context=bridge.context();if(context.tab!=='score'||!context.pageCount||context.correcting){$('scoreNodStatus').textContent='請先開啟一首歌曲，並關閉標記校正';return;}lastSong=context.songId;nod.reset();nod.interval=Number($('scoreNodInterval').value);heldNumber=0;$('scoreNodCount').textContent='0';await camera.start({width:320,targetFps:24,delegate:'CPU'});}
function stop(reason='點頭攝影機已關閉'){camera.stop(reason);nod.reset();active=loading=false;hud.hidden=true;}
$('scoreNodStart').onclick=start;$('scoreNodStop').onclick=()=>stop();$('scoreNodQuickStop').onclick=()=>stop();$('scoreNodCalibrate').onclick=()=>{nod.startCalibration(performance.now());heldNumber=0;$('scoreNodStatus').textContent=nod.message;};
$('scoreNodInterval').oninput=()=>{const ms=Number($('scoreNodInterval').value);nod.setInterval(ms);$('scoreNodSeconds').textContent=(ms/1000).toFixed(1);heldNumber=0;heldUntil=0;$('scoreNodStatus').textContent='間隔已套用，上一組未完成動作已取消';};
const timer=setInterval(()=>{const context=bridge.context();if((active||loading)&&(context.tab!=='score'||context.correcting)){stop('離開樂譜或進入校正，已關閉攝影機');return;}if(!active)return;if(context.songId!==lastSong){lastSong=context.songId;nod.loseFace('切換歌曲，取消上一組動作');}nod.tick(performance.now());const metrics=camera.stats();$('scoreNodAngles').textContent='相對角度 '+(nod.relative??0).toFixed(1)+'° · 實際辨識 '+metrics.inferenceFps.toFixed(1)+' FPS';$('scoreNodCount').textContent=performance.now()<=heldUntil?heldNumber:nod.count;$('scoreNodState').textContent=nod.calibration?'校準中':nod.phase==='READY'?'可點頭':nod.phase==='DOWN'?'請回原位':nod.phase==='COOLDOWN'?'已翻頁':nod.baseline===null?'請校準':'等待回原位';if(nod.cancelReason)$('scoreNodStatus').textContent=nod.cancelReason;},100);
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop('進入背景，攝影機已關閉；返回後請重新啟動與校準');});window.addEventListener('pagehide',()=>{stop();});

$('scoreNodSensitivity').oninput=()=>{nod.threshold=Number($('scoreNodSensitivity').value);$('scoreNodDegrees').textContent=nod.threshold;nod.loseFace('幅度已調整，請回到原位再點頭');};
