'use strict';
const {chords,parse,validate}=ScoreCore;
const SEED={"version":1,"title":"在水一方","artist":"鄧麗君","key":"C","meter":"4/4","capo":null,"bpm":80,"rows":[{"section":"主歌 · 第一遍","text":"綠[C]草蒼[Am]蒼白[Dm]霧茫[G]茫","beats":16,"source":"p001 第一譜列；弱起綠合併入句，有移至下句；以有起點分行"},{"section":"","text":"有[F]位佳[Em]人在[Dm]水[G]一[C]方","beats":16,"source":"p001 第一至二譜列第一結尾；下遍弱起綠移至下句"},{"section":"主歌 · 第二遍","text":"綠[C]草萋[Am]萋白[Dm]霧迷[G]離","beats":16,"source":"p001 第一譜列第二行歌詞；包括前一結尾末拍的綠"},{"section":"","text":"有[F]位佳[Em]人靠[Dm]水[G]而[C]居","beats":17,"source":"p001 第一至二譜列第二結尾；有為 1 拍弱起，加後續 4 小節"},{"section":"副歌 · 第一遍","text":"[Am]我願逆流[Em]而上","beats":8,"source":"p001 第二至三譜列 Am/Em 各 4 拍"},{"section":"","text":"[F]依偎在他身[G]旁","beats":7,"source":"p001 第三譜列 F/G；句尾無的 1 拍移入下一句"},{"section":"","text":"無[Em]奈前有險[Dm]灘","beats":8,"source":"p001 第三譜列；含上句移入無，末拍道移下句"},{"section":"","text":"道[F]路又遠又[G]長","beats":9,"source":"p001 第三至四譜列；道的 1 拍加 F/G 兩小節"},{"section":"","text":"[Am]我願順水[Em]而下","beats":8,"source":"p001 第四譜列 Am/Em 各 4 拍"},{"section":"","text":"[F]找尋他的方[G]向","beats":7,"source":"p001 第四譜列至 p002 第一譜列；卻的 1 拍移下句"},{"section":"","text":"卻[Em]見依稀彷[Dm]彿","beats":8,"source":"p002 第一譜列；含卻，末拍她移下句；不拆散彷彿"},{"section":"","text":"她[F]在水的[G]中[C]央","beats":9,"source":"p002 第一譜列與第一結尾；含她的 1 拍"},{"section":"副歌 · 第二遍","text":"[Am]我願逆流[Em]而上","beats":8,"source":"p001 第二至三譜列 Am/Em 各 4 拍"},{"section":"","text":"[F]與她輕言細[G]語","beats":7,"source":"p001 第三譜列 F/G；句尾無的 1 拍移入下一句"},{"section":"","text":"無[Em]奈前有險[Dm]灘","beats":8,"source":"p001 第三譜列；含上句移入無，末拍道移下句"},{"section":"","text":"道[F]路曲折無[G]已","beats":9,"source":"p001 第三至四譜列；道的 1 拍加 F/G 兩小節"},{"section":"","text":"[Am]我願順水[Em]而下","beats":8,"source":"p001 第四譜列 Am/Em 各 4 拍"},{"section":"","text":"[F]找尋他的蹤[G]跡","beats":7,"source":"p001 第四譜列至 p002 第一譜列；卻的 1 拍移下句"},{"section":"","text":"卻[Em]見依稀彷[Dm]彿","beats":8,"source":"p002 第一譜列；含卻，末拍她移下句；不拆散彷彿"},{"section":"","text":"她[F]在水的[G]中[C]立","beats":8,"source":"p002 第一譜列與第二結尾；末拍綠移入尾段，原文中立待校對"},{"section":"尾段","text":"綠[C]草蒼[Am]蒼白[Dm]霧茫[G]茫","beats":16,"source":"p002 第二譜列；前一結尾的綠移入本句"},{"section":"","text":"有[F]位佳[Em]人在[Dm]水[G]一[C]方","beats":17,"source":"p002 第二至三譜列；包括有的 1 拍及句末延音"},{"section":"收尾","text":"[C]_","beats":4,"source":"p002 最後 C 小節含休止 4 拍"}],"sourcePages":[{"id":"p001","file":"references/water-1.png","originalPage":1},{"id":"p002","file":"references/water-2.png","originalPage":2}],"sourceNotes":["依使用者提供的心動吉他兩頁譜轉錄；譜面標示 C、4/4、四分音符 80。","主歌與副歌依第一、第二結尾展開；本譜無獨立前奏或間奏，不另行編造。","弱起 1 拍，57 個完整小節，共 229 拍；另加 4 拍預備。每行是樂句提示，非逐拍游標。","原譜第二遍結尾顯示「她在水的中立」，疑似印刷／歌詞對位錯誤；暫保留原文字，請試唱校對。","保留原譜他／她與順水用字；Capo 未標示。","依完整詞句換行，通常 4～8 字；弱起歸入所屬句，彷彿、白霧茫茫等詞組不跨行。重分每行拍數，總計仍為 229 拍。"]};
const KEY="smart-guitar-7dbc202fa5da52c0e66a";let state={song:structuredClone(SEED),page:0,rows:10,size:28,favorite:false};
let storageError=false;try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved){validate(saved.song);state={...state,...saved};state.rows=[8,10].includes(state.rows)?state.rows:10;state.size=[24,28,32].includes(state.size)?state.size:28;state.page=Number.isInteger(state.page)?state.page:0;}}catch(e){storageError=true;}
// Upgrade only untouched v1 transcription, preserving custom lyrics and practice settings.
const PREVIOUS_ROWS=["綠","[C]草蒼[Am]蒼白","[Dm]霧茫[G]茫有","[F]位佳[Em]人在","[Dm]水[G]一[C]方綠","[C]草萋[Am]萋白","[Dm]霧迷[G]離有","[F]位佳[Em]人靠","[Dm]水[G]而[C]居","[Am]我願逆流[Em]而上","[F]依偎在他身[G]旁無","[Em]奈前有險[Dm]灘道","[F]路又遠又[G]長","[Am]我願順水[Em]而下","[F]找尋他的方[G]向卻","[Em]見依稀彷[Dm]彿她","[F]在水的[G]中[C]央","[Am]我願逆流[Em]而上","[F]與她輕言細[G]語無","[Em]奈前有險[Dm]灘道","[F]路曲折無[G]已","[Am]我願順水[Em]而下","[F]找尋他的蹤[G]跡卻","[Em]見依稀彷[Dm]彿她","[F]在水的[G]中[C]立綠","[C]草蒼[Am]蒼白","[Dm]霧茫[G]茫有","[F]位佳[Em]人在","[Dm]水[G]一[C]方","[C]_"];
if(state.song.title===SEED.title&&state.song.rows.length===PREVIOUS_ROWS.length&&state.song.rows.every((r,i)=>r.text===PREVIOUS_ROWS[i])){state.song=structuredClone(SEED);state.page=0;}
const SONG_BEATS=[16,16,16,17,8,7,8,9,8,7,8,9,8,7,8,9,8,7,8,8,16,17,4];
function fillTiming(song){song.rows.forEach((r,i)=>{if(r.beats===undefined)r.beats=song.title===SEED.title&&song.rows.length===SEED.rows.length&&r.text===SEED.rows[i].text?SONG_BEATS[i]:8;});}
fillTiming(state.song);
state.mode=state.mode==='pages'?'pages':'continuous';
state.scrollBpm=Number.isFinite(state.scrollBpm)&&state.scrollBpm>=20&&state.scrollBpm<=300?state.scrollBpm:(80);
state.countIn=[0,4,8].includes(state.countIn)?state.countIn:4;
const $=s=>document.querySelector(s);const create=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;};
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageError=false;}catch(e){storageError=true;toast('瀏覽器無法儲存，請從歌曲工具匯出備份。');}status();}
function status(){$('#saveStatus').textContent=storageError?'尚未儲存 · 請匯出備份':'換和弦提示 · 非逐拍節奏譜';}
function render(){
 const pages=Math.ceil(state.song.rows.length/state.rows);state.page=Math.max(0,Math.min(state.page,pages-1));
 $('#songKey').textContent=state.song.key?state.song.key+' 調':'調性待確認';$('#songMeter').textContent=state.song.meter??'拍號待確認';$('#title').textContent=state.song.title;$('#artist').textContent=state.song.artist;document.title=state.song.title+' · 智慧吉他譜';$('#capo').textContent='Capo '+(state.song.capo??'待確認');$('#bpm').textContent='BPM '+(state.song.bpm??'待確認');
 $('#favorite').textContent=state.favorite?'♥':'♡';$('#favorite').style.color=state.favorite?'#ee45ba':'';$('#favorite').setAttribute('aria-pressed',String(state.favorite));
 document.documentElement.style.setProperty('--font',state.size+'px');document.documentElement.style.setProperty('--box',(state.size+15)+'px');$('#score').style.setProperty('--rows',state.rows);
 const score=$('#score');score.replaceChildren();
 document.body.classList.toggle('continuous',state.mode==='continuous');
 if(state.mode==='continuous')window.scrollTo(0,0);
 const visible=state.mode==='continuous'?state.song.rows:state.song.rows.slice(state.page*state.rows,(state.page+1)*state.rows);
 for(const row of visible){
  const el=create('div',undefined,'score-row'+(row.text.includes('_')?' instrumental':''));
  if(row.section)el.append(create('span',row.section,'section-label'));
  const content=create('div',undefined,'row-content');
  for(const token of parse(row.text)){
   const unit=create('span',token.text,'lyric'+(token.chord?' mark':''));
   if(token.chord){const info=chords.find(c=>c[0]===token.chord);unit.style.setProperty('--color',info?info[2]:'#c6cbd2');const label=create('span',undefined,'chord-label');if(info)label.append(create('b',info[1]),create('small',token.chord));else label.append(create('b',token.chord));unit.append(label);unit.title=info?'按鍵 '+info[1]+' · '+token.chord:token.chord+'：尚未設定按鍵';}
   content.append(unit);
  }el.append(content);score.append(el);
 }
 if(state.mode!=='continuous')for(let i=visible.length;i<state.rows;i++)score.append(create('div',undefined,'score-row empty'));
 $('#page').textContent=`第 ${state.page+1} / ${pages} 頁`;$('#prev').disabled=state.page===0;$('#next').disabled=state.page===pages-1;$('#sectionStatus').textContent=state.mode==='continuous'?`全曲連續 · ${state.song.rows.length} 行`:`每頁 ${state.rows} 行 · ${state.song.rows.length} 行完整展開`;status();
 if(typeof refreshScroll==='function')refreshScroll();
}
for(const [chord,n,color] of chords){const el=create('div',undefined,'legend-item');el.style.setProperty('--color',color);el.append(create('b',n),create('small',chord),create('i'));$('#legend').append(el);}
function turn(delta){if(state.mode==='continuous')return;state.page+=delta;render();save();window.scrollTo({top:0,behavior:'instant'});}
$('#prev').onclick=()=>turn(-1);$('#next').onclick=()=>turn(1);$('#favorite').onclick=()=>{state.favorite=!state.favorite;render();save();};
document.addEventListener('keydown',e=>{if($('#dialog').open||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();turn(1);}if(e.key==='ArrowLeft'){e.preventDefault();turn(-1);}});
let touch=null;$('#score').addEventListener('touchstart',e=>{touch={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY};},{passive:true});$('#score').addEventListener('touchend',e=>{if(!touch)return;const dx=e.changedTouches[0].clientX-touch.x,dy=e.changedTouches[0].clientY-touch.y;if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy)*1.5)turn(dx<0?1:-1);touch=null;},{passive:true});
function modal(title){if(typeof pauseScroll==='function')pauseScroll();$('#dialogTitle').textContent=title;$('#dialogBody').replaceChildren();if(!$('#dialog').open)$('#dialog').showModal();return $('#dialogBody');}
$('#close').onclick=()=>$('#dialog').close();$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
function field(parent,label,control){const line=create('label',undefined,'field');line.append(create('span',label),control);parent.append(line);}
function select(options,value,fn){const s=create('select');for(const [v,label]of options){const o=create('option',label);o.value=v;s.append(o);}s.value=value;s.onchange=()=>fn(s.value);return s;}
$('#settings').onclick=()=>{const b=modal('閱讀設定');field(b,'每頁行數',select([[10,'10 行 · 精簡'],[8,'8 行 · 寬鬆']],state.rows,v=>{const anchor=state.page*state.rows;state.rows=+v;state.page=Math.floor(anchor/state.rows);render();save();}));field(b,'歌詞大小',select([[24,'小'],[28,'標準'],[32,'大']],state.size,v=>{state.size=+v;render();save();}));b.append(create('p','黑底與七色按鍵固定不變。小螢幕可上下捲動；左右滑動可翻頁。','hint'));};
$('#page').onclick=()=>{const b=modal('前往頁面'),list=create('div',undefined,'page-options');for(let i=0;i<Math.ceil(state.song.rows.length/state.rows);i++){const btn=create('button','第 '+(i+1)+' 頁');btn.onclick=()=>{state.page=i;render();save();$('#dialog').close();window.scrollTo(0,0);};list.append(btn);}b.append(list);};
$('#source').onclick=()=>{const b=modal('原始樂譜 · '+state.song.title);b.append(create('p','換和弦提示，非逐拍節奏譜。'+(state.song.sourceNotes||[]).join('；'),'hint'));for(const [i,page]of (state.song.sourcePages||[]).entries()){if(!/^references\/water-\d+\.(png|jpe?g)$/.test(page.file))continue;b.append(create('h3','來源頁 '+(page.originalPage??(i+1))));const img=create('img',undefined,'source-img');img.src=page.file;img.alt='原譜 '+(i+1);b.append(img);}};
function tool(b,label,fn){const btn=create('button',label,'tool');btn.onclick=fn;b.append(btn);}
$('#more').onclick=()=>{const b=modal('歌曲工具');tool(b,'✎  校對歌詞與和弦',edit);tool(b,'↓  匯出歌曲備份',exportSong);tool(b,'↑  匯入歌曲備份',()=>$('#file').click());b.append(create('p','此歌曲支援校對、翻頁與本機保存；每首歌的設定分開儲存。檔案備份可帶到另一個瀏覽器；沒有自動雲端同步。','hint'));};
function edit(){const b=modal('校對歌詞與和弦');b.append(create('p','在換和弦的字前加上 [C]、[Dm] 等標記，例如：你[C]問我愛你[Em]有多深。空方塊使用 [C]_。這是換和弦位置，不代表每次撥弦。','hint'));const title=create('input');title.value=state.song.title;field(b,'歌名',title);const artist=create('input');artist.value=state.song.artist;field(b,'歌手',artist);const bpm=create('input');bpm.type='number';bpm.min=20;bpm.max=300;bpm.placeholder='待確認';bpm.value=state.song.bpm??'';field(b,'BPM',bpm);const capo=create('input');capo.type='number';capo.min=0;capo.max=12;capo.placeholder='待確認';capo.value=state.song.capo??'';field(b,'Capo',capo);
 const fields=[];state.song.rows.forEach((row,i)=>{const wrap=create('div',undefined,'edit-row');wrap.append(create('small',`第 ${i+1} 行 · ${row.source}`,'hint'));const s=create('input');s.value=row.section;s.placeholder='段落名稱（可留白）';s.setAttribute('aria-label','第 '+(i+1)+' 行段落');const t=create('textarea');t.value=row.text;t.setAttribute('aria-label','第 '+(i+1)+' 行歌詞和弦');wrap.append(s,t);b.append(wrap);fields.push({s,t,source:row.source,beats:row.beats});});const bottom=create('div',undefined,'sticky-save'),btn=create('button','儲存校對結果','primary');btn.onclick=()=>{const candidate={...state.song,title:title.value.trim(),artist:artist.value.trim(),bpm:bpm.value===''?null:Number(bpm.value),capo:capo.value===''?null:Number(capo.value),rows:fields.map(x=>({section:x.s.value,text:x.t.value,source:x.source,beats:x.beats}))};try{validate(candidate);state.song=candidate;render();save();if(!storageError)toast('已儲存校對結果');$('#dialog').close();}catch(e){toast(e.message);}};bottom.append(btn);b.append(bottom);
}
function exportSong(){const blob=new Blob([JSON.stringify(state.song,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=create('a');a.href=url;a.download="zai-shui-yi-fang-校對備份.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已匯出歌曲資料；原圖保留於應用程式資料夾。');}
$('#file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1024*1024)throw Error('備份檔不可超過 1 MB。');const song=validate(JSON.parse(await file.text()));if(!confirm('以匯入資料取代目前歌曲？建議先匯出目前版本。'))return;fillTiming(song);state.song=song;state.page=0;resetScroll();render();save();if(!storageError)toast('匯入完成');$('#dialog').close();}catch(err){toast('匯入失敗：'+err.message);}finally{e.target.value='';}};
render();if(storageError)toast('先前資料無法讀取或儲存不可用，目前顯示初始歌曲。');

