import {searchPoems,matchesSearch} from './core.js';
import {LEVELS,SORTS,familiarityOf,filterFamiliarity,familiarityCounts} from './familiarity.js';
const e=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const blankRegistry={byKey:new Map(),resolve:(type,id)=>`${type}:${id}`};
let context={state:{},registry:blankRegistry,options:{filters:[],sort:'default',selected:[],batch:false},visible:new Set()};
export function configureFamiliarity(state,registry,options){context={state,registry,options,visible:new Set()};}
export function currentFamiliarityUI(){return context;}
export function statusOf(type,id){return familiarityOf(context.state,context.registry.resolve(type,id));}
export function filterItems(items,type){return filterFamiliarity(items,type,context.state,context.registry,context.options);}
export function badge(type,id,prefix=''){
 const key=context.registry.resolve(type,id),level=familiarityOf(context.state,key),ref=context.registry.byKey.get(key);
 return `<button class="fam-badge fam-${level}" data-act="fam-open" data-key="${e(key)}" aria-label="${e(prefix|| (type==='poem'?'全篇':'本句'))}《${e(ref?.poem.title||'詩詞')}》：${LEVELS[level].label}，設定背誦熟悉度"><span class="fam-dot" aria-hidden="true"></span>${prefix?`<span class="fam-prefix">${e(prefix)}</span>`:''}${LEVELS[level].short}</button>`;
}
export function itemTools(type,id,prefix=''){
 const key=context.registry.resolve(type,id),o=context.options;
 return `<span class="fam-item-tools">${o.batch?`<label class="fam-check"><input type="checkbox" data-fam-select="${e(key)}" ${o.selected.includes(key)?'checked':''} aria-label="選取 ${e(context.registry.byKey.get(key)?.poem.title||'此內容')}"><span>選取</span></label>`:''}${badge(type,id,prefix)}</span>`;
}
export function quoteTools(q,batch=true){return `<div class="fam-quote-tools">${batch?itemTools('quote',q.id,'本句'):badge('quote',q.id,'本句')}${badge('poem',q.poem.id,'全篇')}</div>`;}
export function controls(items,type,{batch=true}={}){
 const o=context.options;for(const item of items)context.visible.add(context.registry.resolve(type,item.id));
 return `<section class="fam-controls" aria-label="背誦熟悉度篩選"><div class="row between wrap"><strong>熟悉度篩選</strong>${batch?`<button class="button text" data-act="fam-batch">${o.batch?'完成批次':'批次標記'}</button>`:''}</div><div class="row wrap section" aria-label="背誦順序">${[['learnedFirst','已背過優先'],['unlearnedFirst','尚未背誦優先']].map(([value,label])=>`<button class="chip ${o.sort===value?'selected':''}" data-act="fam-order" data-value="${value}" aria-pressed="${o.sort===value}">${label}</button>`).join('')}</div><div class="fam-filters"><button class="chip${!o.filters.length?' selected':''}" data-act="fam-filter" data-value="all" aria-pressed="${!o.filters.length}">全部</button>${Object.entries(LEVELS).map(([id,l])=>`<button class="chip fam-${id}${o.filters.includes(id)?' selected':''}" data-act="fam-filter" data-value="${id}" aria-pressed="${o.filters.includes(id)}"><span class="fam-dot" aria-hidden="true"></span>${l.short}</button>`).join('')}<button class="button text" data-act="fam-unfamiliar">只看不熟（黃＋紅）</button></div><div class="row between wrap"><span class="small muted" role="status">${o.filters.length?'已選：'+o.filters.map(x=>LEVELS[x].short).join('＋'):'顯示全部熟悉度'} · 可複選</span><label class="fam-sort">排序 <select data-fam-sort>${Object.entries(SORTS).map(([id,label])=>`<option value="${id}" ${o.sort===id?'selected':''}>${label}</option>`).join('')}</select></label></div>${o.batch?`<div class="fam-batchbar"><span>已選 ${o.selected.length} 項</span><button class="button text" data-act="fam-all">全選目前結果</button><button class="button text" data-act="fam-none">取消選取</button><button class="button primary" data-act="fam-batch-set" ${o.selected.length?'':'disabled'}>設定熟悉度</button></div>`:''}</section>`;
}
export function selector(refs,review=false){return `<p class="small muted">${refs.length===1?`${refs[0].contentType==='poem'?'全篇':'本句'} · ${e(refs[0].poem.title)}`:`已選 ${refs.length} 項`}。點選即儲存${review?'並記錄複習時間':''}。</p><div class="fam-selector">${Object.entries(LEVELS).map(([id,l])=>`<button class="fam-choice fam-${id}" data-act="fam-set" data-value="${id}"><span class="fam-dot" aria-hidden="true"></span>${l.label}${id==='unlearned'?'（清除標記）':''}</button>`).join('')}</div><p class="small muted">全篇與本句分開記錄；收藏不受影響。</p>`;}
export function homeFamiliarity(){return `<section class="fh-home section"><div><h2>我的背誦</h2><p class="small muted">快速標記，集中複習不熟的內容。</p></div><a class="button primary" href="#/my-recitation">管理背誦 →</a><div class="fam-home-counts">${stats('poem')}</div><a class="button text" href="#/my-recitation?levels=weak,shaky">複習全部未熟（黃＋紅）</a></section>`;}
function stats(type){const counts=familiarityCounts(context.registry,context.state,type);return Object.entries(LEVELS).map(([id,l])=>`<span class="fam-stat fam-${id}"><span class="fam-dot" aria-hidden="true"></span>${l.short}<strong>${counts[id]}</strong></span>`).join('');}
export function managerView(type='poem',query=''){
 const all=[...context.registry.byKey.values()].filter(r=>r.contentType===type).map(r=>type==='poem'?r.poem:{...r.quote,id:r.contentId});const searched=type==='poem'?searchPoems(all,query):all.filter(q=>matchesSearch(`${q.text}${q.poem.title}${q.poem.author}`,query));const found=filterItems(searched,type);
 return `<div class="page-heading recitation-heading"><p class="eyebrow">標記 → 篩選 → 集中背誦</p><h1>我的背誦</h1><p class="creator-credit">由 Vincent Chiou 製作於加拿大</p></div><div class="filters"><a class="chip ${type==='poem'?'selected':''}" href="#/my-recitation?kind=poem">整首作品</a><a class="chip ${type==='quote'?'selected':''}" href="#/my-recitation?kind=quote">名句</a></div><form class="search" id="recitation-search-form" role="search"><label class="sr-only" for="recitation-search">搜尋詩名、作者或詩句</label><input id="recitation-search" type="search" value="${e(query)}" placeholder="搜尋詩名、作者、詩句…" enterkeyhint="search"><button type="submit" class="button soft">搜尋</button></form><details class="recitation-options" ${context.options.batch||context.options.filters.length?'open':''}><summary>篩選熟悉度・排序・批次標記</summary>${controls(found,type)}</details><p class="small muted">符合 ${found.length} 項。全部未熟只包含黃色與紅色。</p>${type==='poem'?poemTable(found):`<div class="poem-list section">${found.map(item=>{const p=type==='poem'?item:item.poem;return `<article class="poem-row">${type==='poem'?itemTools(type,item.id,'全篇'):quoteTools(item)}<h3>${e(p.title)}</h3><p class="small muted">${e(p.author)} · ${e(p.dynasty)}</p>${type==='quote'?`<p class="poem-text fam-excerpt">${e(item.text)}</p>`:''}<a class="button soft section" href="#/${type==='poem'?'practice':'couplet'}/${e(item.id)}">開始背誦</a></article>`;}).join('')}</div>`}${found.length?'':'<p class="empty">沒有符合的內容，可調整上方篩選。</p>'}<div class="fam-stats">${stats(type)}</div><div class="row wrap section">${[['weak','複習很不熟'],['shaky','複習不太熟'],['weak,shaky','複習全部未熟']].map(([v,l])=>`<a class="button soft" href="#/my-recitation?kind=${type}&levels=${v}">${l}</a>`).join('')}</div><div class="row wrap section"><a class="button soft" href="#/today">今日推薦與飛花令</a><button class="button" data-act="export">匯出背誦紀錄</button><button class="button" data-act="import">匯入背誦紀錄</button><input type="file" id="backup-file" accept="application/json,.json" hidden></div>`;
}

function poemTable(items){
 return '<div class="recitation-table-wrap section" tabindex="0" role="region" aria-label="全部作品快速表格，可上下捲動"><table class="recitation-table"><caption class="sr-only">整首作品熟悉度快速瀏覽</caption><thead><tr><th scope="col">類型</th><th scope="col">作品／作者</th><th scope="col">熟悉度</th><th scope="col">查看</th></tr></thead><tbody>'+items.map(p=>`<tr><td><span class="work-type ${p.type==='唐詩'?'work-type-tang':p.type==='宋詞'?'work-type-song':'work-type-other'}">${e(p.type)}</span></td><th scope="row"><span class="recitation-title">${e(p.title)}</span><span class="recitation-author">${e(p.author)}</span></th><td>${itemTools('poem',p.id)}</td><td><a class="recitation-open" href="#/read/${e(p.id)}" aria-label="查看${e(p.title)}">查看<span aria-hidden="true"> ›</span></a></td></tr>`).join('')+'</tbody></table></div>';
}
