import {badge,itemTools,quoteTools,filterItems,controls,homeFamiliarity,statusOf} from './familiarity-ui.js';
import { escapeHTML as e, dailyPoem, duePoems, maskLine, quoteEntries, searchPoems, THEMES, SPEEDS, RATINGS } from './core.js';
const paths = {
  home:'M3 11 12 3l9 8M5 10v11h14V10M9 21v-7h6v7',
  book:'M12 5v16M3 3c4 0 6 0 9 2 3-2 5-2 9-2v16c-4 0-6 0-9 2-3-2-5-2-9-2Z',
  star:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z',
  brain:'M9 4C6 2 3 5 5 8 1 10 3 15 6 15c-1 4 4 6 6 2V5c0-3-3-4-4-1M15 4c3-2 6 1 4 4 4 2 2 7-1 7 1 4-4 6-6 2M6 10l3 2M18 10l-3 2',
  heart:'M20.5 4.5c-2-2-5-2-8.5 1.5C8.5 2.5 5.5 2.5 3.5 4.5c-3 3-1 7 8.5 15 9.5-8 11.5-12 8.5-15Z',
  settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1ZM12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8',
  arrow:'M5 12h14m-6-6 6 6-6 6',back:'M19 12H5m6-6-6 6 6 6',close:'m6 6 12 12M18 6 6 18',
  search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14m5 12 6 6',
  play:'m8 4 12 8-12 8Z',pause:'M8 4v16M16 4v16',replay:'M4 10a8 8 0 1 1 1 8M4 4v6h6',
  hill:'m2 20 7-14 4 7 3-5 6 12ZM6 12l3 2 3-2',person:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8M4 21v-2a8 8 0 0 1 16 0v2',
  chart:'M4 20V10M12 20V4M20 20v-7',check:'m4 12 5 5L20 6',download:'M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4',
  cloud:'M7 18H6a4 4 0 1 1 1-8 6 6 0 0 1 11-1 4.5 4.5 0 0 1 0 9h-1M9 16l3 3 4-5',
  moon:'M20 15A9 9 0 0 1 9 3a9 9 0 1 0 11 12',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1',
  leaf:'M20 3C8 1 1 8 5 16s14 2 15-13ZM5 20 16 7',phone:'M7 2h10a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2Zm3 17h4'
};
export const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name] || paths.book}"/></svg>`;
const link = (label, target, style = 'button') => `<a class="${style}" href="#${e(target)}">${label}</a>`;
export const button = (label, act, attrs = '', style = 'button') => `<button class="${style}" data-act="${act}" ${attrs}>${label}</button>`;
const dateLabel = date => new Intl.DateTimeFormat('zh-TW', { month: 'long', day: 'numeric', weekday: 'long' }).format(date);
const dueLabel = date => new Intl.DateTimeFormat('zh-TW', { month:'numeric', day:'numeric', hour:'2-digit', minute:'2-digit' }).format(new Date(date));
const shortQuote = text => text.replace(/([，。；？！])/gu, '$1\n').trim();
function hero(poem, text = poem.famousLines[0], label = '今日一詩', isLink = true) {
  return `<${isLink ? 'a' : 'div'} class="hero" ${isLink ? `href="#/read/${e(poem.id)}"` : ''}>
    <div class="row between" style="width:100%"><span class="eyebrow">${icon('moon')}${label}</span><span class="stamp">詩意日常</span></div>
    <div class="quote-text">${e(shortQuote(text))}</div>
    <div class="hero-bottom"><div class="author-block"><strong>${e(poem.title)}</strong>${e(poem.author)} · ${e(poem.dynasty)}</div>${isLink ? `<span class="arrow">${icon('arrow')}</span>` : ''}</div>
  </${isLink ? 'a' : 'div'}>`;
}
export function row(poem, target = 'read', status = '') {
  return `<article class="poem-row">${itemTools('poem',poem.id)}<a class="fam-row-link" href="#/${target}/${e(poem.id)}"><h3>${e(poem.title)}</h3><div class="row-meta">${e(poem.author)} · ${e(poem.dynasty)}　${e(poem.type)}</div><p class="row-quote">${e(poem.famousLines[0])}</p>${status ? `<span class="row-label">${e(status)}</span>` : ''}</a></article>`;
}
export function empty(title, description, target = '/library') { return `<div class="empty">${icon('book')}<h2>${e(title)}</h2><p>${e(description)}</p>${link('去看看詩詞', target, 'button soft')}</div>`; }
export function shell(content, tab, storageError = '') {
  if(tab==='today')tab='my-recitation';
  const tabs = [['my-recitation','我的背誦','home'],['library','詩詞','book'],['quotes','名句','star'],['study','背誦','brain'],['favorites','收藏','heart']];
  return `<div class="shell"><header class="topbar"><a class="brand" href="#/my-recitation"><img src="./icons/icon-192.png" alt="" width="40" height="40"><span>詩詞隨身背<span class="brand-sub">　POETRY, EVERY DAY</span><span class="brand-creator">Vincent Chiou · 加拿大</span></span></a><div class="top-actions">${button(icon('phone'), 'install', 'aria-label="安裝與手機驗證"','icon-button')}${button(`${icon('sun')}<span>配色</span>`, 'settings','aria-label="配色與閱讀設定"','button text')}</div></header>${storageError ? `<div class="offline-banner" role="alert">${e(storageError)}</div>` : ''}<main id="main">${content}</main></div><nav class="tabbar" aria-label="主要導覽">${tabs.map(([id,label,symbol]) => `<a href="#/${id}" ${id===tab?'aria-current="page"':''} class="${id===tab?'active':''}">${icon(symbol)}<span>${label}</span></a>`).join('')}</nav>`;
}
export function todayView(poems, state, offline) {
  const today=dailyPoem(poems),studied=Object.values(state.progress).filter(p=>p.reviewCount>0).length,due=duePoems(poems,state).length;
  const tiles=[['唐詩','sun','/library?category=唐詩'],['宋詞','moon','/library?category=宋詞'],['名家','person','/authors'],['山水名勝','hill','/locations']];
  return `<div class="today-intro"><p class="eyebrow">${dateLabel(new Date())}</p><h1>今天，讓心裡住一句詩。</h1></div><div class="home-grid"><div>${hero(today)}${badge('poem',today.id,'全篇')}<div class="status-line">${icon(offline==='ready'?'check':'cloud')}<span id="offline-label">${offline==='ready'?'已備妥離線閱讀':'正在準備離線閱讀'}</span>${button('查看','install','','')}</div></div><div><section class="practice-prompt"><div class="row between"><span class="eyebrow">練習自評</span><div class="progress-ring" style="--progress:${studied/poems.length*100}"><span>${studied}/${poems.length}</span></div></div><h2>熟悉的詩，慢慢找回來</h2><p>${studied ? `已完成 ${studied} 首詩的練習自評。` : '從記得的一句，開始今天的練習。'}<br>${due} 首待學習或複習</p>${link(`${icon('brain')}開始背誦`,'/study','button primary full')}</section><div class="explore-grid">${tiles.map(([label,symbol,target])=>link(`<span class="tile-icon">${icon(symbol)}</span><span>${label}</span>`,target,'explore-tile')).join('')}</div></div></div><section class="section"><div class="section-heading"><h2>熟悉的名句</h2>${link('再讀一句 →','/quotes','')}</div><div class="poem-list">${poems.filter(p=>['su-shui','wang-shan'].includes(p.id)).map(p=>row(p)).join('')}</div></section>`;
}
export function libraryView(poems, query, category) {
 const found=filterItems(searchPoems(poems,query,category),'poem');
  return `<div class="page-heading"><p class="eyebrow">在字裡行間，再次相遇</p><h1>我的隨身詩集</h1><p><a class="button soft section" href="#/catalogue">全部作品總覽與比較 →</a></p></div><form class="search" role="search" id="search-form">${icon('search')}<label class="sr-only" for="search-input">搜尋詩名、作者、詩句、景點</label><input id="search-input" name="query" type="search" placeholder="搜尋明月、蘇軾、黃鶴樓…" value="${e(query)}" autocomplete="off"></form><div class="filters">${['','唐詩','宋詞'].map(c=>button(c||'全部作品','filter',`data-value="${c}" aria-pressed="${c===category}"`,'chip'+(c===category?' selected':''))).join('')}${category&&!['唐詩','宋詞'].includes(category)?button(`${e(category)} ×`,'filter','data-value=""','chip selected'):''}</div>${controls(found,'poem')}<div class="section-heading"><span id="result-count" class="muted small">${found.length} 首作品</span><div class="row">${link('名家','/authors','button text')}${link('景點','/locations','button text')}</div></div><div id="search-results">${libraryResults(poems,query,category)}</div>`;
}
export function libraryResults(poems, query, category) { const found=filterItems(searchPoems(poems,query,category),'poem');return found.length ? `<div class="poem-list">${found.map(p=>row(p)).join('')}</div>` : empty('還沒找到這首詩','試試作者、詩句或景點名稱。'); }
export function categoriesView(poems, type) {
  const location=type==='locations',names=[...new Set(poems.flatMap(p=>location?p.locations:[p.author]))].sort((a,b)=>a.localeCompare(b,'zh-TW'));
  return `<div class="page-heading"><p class="eyebrow">${location?'把風景，讀成一句詩':'重逢熟悉的名字'}</p><h1>${location?'跟著詩詞去旅行':'名家詩詞'}</h1></div><div class="category-grid">${names.map(name=>link(`${icon(location?'hill':'person')}<h3>${e(name)}</h3><small>${poems.filter(p=>location?p.locations.includes(name):p.author===name).length} 首作品</small>`,`/library?category=${encodeURIComponent(name)}`,'')).join('')}</div>`;
}
export function lineMarkup(poem, line, index, zhuyin) {
  const entries=poem.difficultCharacters.filter(d=>d.lineContext===line);
  const characters=[...line].map(c=>{const d=entries.find(x=>x.character===c);return d?button(e(c),'character',`data-poem="${e(poem.id)}" data-character="${e(c)}" data-line="${index}" aria-label="${e(c)}，查看字詞說明"`,'char-link'):e(c);}).join('');
  return `<div class="poem-line" id="line-${index}"><div class="poem-text ${poem.famousLines.some(q=>q.includes(line))?'famous':''}">${characters}</div>${zhuyin&&entries.length?`<div class="zhuyin-row">${entries.map(d=>button(`${e(d.character)} <span>${e(d.zhuyin)}</span>`,'character',`data-poem="${e(poem.id)}" data-character="${e(d.character)}" data-line="${index}"`,'zhuyin-button')).join('')}</div>`:''}</div>`;
}
export function readerView(poem,state) {
  const favorite=state.progress[poem.id]?.isFavorite;
  return `<article class="reader"><div class="row between">${link(`${icon('back')}詩集`,'/library','backlink')}${button(icon('heart'),'favorite',`data-poem="${e(poem.id)}" aria-label="${favorite?'取消收藏':'收藏詩詞'}" aria-pressed="${Boolean(favorite)}"`,'icon-button')}</div><header class="reader-title"><span class="pill">${e(poem.type)}</span><h1>${e(poem.title)}</h1><p class="muted">${e(poem.author)} ｜ ${e(poem.dynasty)}</p>${badge('poem',poem.id,'全篇')}</header><div class="poem-lines">${poem.lines.map((line,i)=>lineMarkup(poem,line,i,state.settings.zhuyin)).join('')}</div>${link(`${icon('brain')}記住這首詩`,`/practice/${e(poem.id)}`,'button primary full')}<section class="reader-section section"><h2>白話解釋</h2><p>${e(poem.translation)}</p></section><section class="reader-section"><h2>創作背景</h2><p>${e(poem.background)}</p></section>${poem.annotations.length?`<section class="reader-section"><h2>字詞小箋</h2>${poem.annotations.map(a=>`<p>${e(a)}</p>`).join('')}</section>`:''}<details class="reader-section"><summary>原文來源與版本</summary><p>${e(poem.textualNote)}</p><p class="source">${e(poem.source)}</p><p class="small muted">白話與背景為學習摘要。景點分類表示文學關聯。</p></details></article><div class="playbar" aria-label="朗讀控制">${button(`${icon('play')}<span id="play-label">朗讀</span>`,'play',`data-poem="${e(poem.id)}" id="play-button" aria-label="朗讀全詩"`,'button primary')}${button(icon('replay'),'replay',`data-poem="${e(poem.id)}" aria-label="從頭重播"`,'icon-button')}<label class="sr-only" for="reader-speed">朗讀速度</label><select id="reader-speed" data-setting="speed">${SPEEDS.map(n=>`<option value="${n}" ${state.settings.speed===n?'selected':''}>${n}×</option>`).join('')}</select>${button(icon('close'),'stop','aria-label="停止朗讀"','icon-button')}</div>`;
}
export function quotesView(poems,state,index) {
  const quotes=quoteEntries(poems),q=quotes[index%quotes.length],favorite=state.quotes.includes(q.id);
  return `<div class="page-heading"><p class="eyebrow">不必背整首，也能留住一句</p><h1>千古名句</h1></div><section class="quote-stage"><div id="quote-swipe">${hero(q.poem,q.text,'每日名句',false)}${quoteTools(q,false)}</div><div class="row between quote-controls">${button(icon('back'),'quote-prev','aria-label="上一句"','icon-button')}<span class="counter">${index+1} / ${quotes.length}　左右滑動</span>${button(icon('arrow'),'quote-next','aria-label="下一句"','icon-button')}</div><div class="row between wrap">${button(`${icon('heart')}${favorite?'已收藏名句':'收藏名句'}`,'quote-favorite',`data-id="${e(q.id)}" aria-pressed="${favorite}"`,'button soft')}${link('讀全篇 →',`/read/${e(q.poem.id)}`,'button text')}</div><div class="quote-explanation">${e(q.poem.translation)}</div></section>`;
}
export function studyView(poems,state) {
  const due=filterItems(duePoems(poems,state),'poem'),available=filterItems(poems,'poem'),studied=Object.values(state.progress).filter(p=>p.reviewCount>0).length;
  return `<div class="page-heading"><p class="eyebrow">不求一字不差，先找回一點記憶</p><h1>今天，一句一句來</h1></div>${homeFamiliarity()}${controls(available,'poem')}<div class="practice-prompt row between wrap"><div><h2>${due.length?'準備好，再讀一遍':'今天的複習完成了'}</h2><p>${studied} 首有練習紀錄 · ${due.length} 首待學習或複習</p></div>${link(`${icon('chart')}學習進度`,'/progress','button soft')}</div><section class="section"><div class="section-heading"><h2>待學習與複習</h2><span class="pill">${due.length} 首</span></div>${due.length?`<div class="poem-list">${due.map(p=>row(p,'practice',state.progress[p.id]?.reviewCount?'該複習了':'尚無複習紀錄')).join('')}</div>`:empty('把今天的詩留在心裡','下次到期時，作品會再次出現在這裡。')}</section><section class="section"><h2>自由練習</h2><div class="filters section">${available.map(p=>`<span class="fam-free-practice">${itemTools('poem',p.id)}${link(e(p.title),`/practice/${p.id}`,'button')}</span>`).join('')}</div></section>`;
}
export function practiceView(poem,state,practice) {
  const {mode,revealed,submitted,rating}=practice;
  return `<article class="practice">${link(`${icon('back')}背誦`,'/study','backlink')}<div class="reader-title"><span class="pill">背誦練習</span><h1>${e(poem.title)}</h1><p class="muted">${e(poem.author)} · ${e(poem.dynasty)}</p>${badge('poem',poem.id,'全篇')}</div><div class="filters" aria-label="背誦模式">${[['read','完整閱讀'],['lines','逐句隱藏'],['words','挖字填空']].map(([id,label])=>button(label,'practice-mode',`data-value="${id}" aria-pressed="${id===mode}"`,'chip'+(id===mode?' selected':''))).join('')}</div><p class="small muted">${mode==='read'?'先讀一遍，再試試逐句隱藏或挖字填空。':'先在心中回答，點擊空白再揭曉答案。'}</p><div class="poem-lines">${poem.lines.map((line,i)=>{const masked=maskLine(line,mode,i,revealed.has(i));return masked===line?`<p class="revealed-line">${e(line)}</p>`:button(e(masked),'reveal',`data-index="${i}" aria-label="第 ${i+1} 句，${e(masked)}，點擊揭曉"`,'mask');}).join('')}</div>${submitted?`<div class="success-card"><h2>${icon('check')} 已記錄這次練習</h2><p>下次複習：${dueLabel(state.progress[poem.id].nextReviewDate)}</p><div class="row wrap section">${link('回到背誦','/study','button primary')}${button('再練一次','practice-again','','button')}</div></div>`:rating?`<section><h2>這次記得多少？</h2><p class="muted small">照實回答，就能在合適的時候再遇見。</p><div class="rating-grid">${RATINGS.map((title,i)=>button(title,'rate',`data-rating="${i}" data-poem="${e(poem.id)}"`)).join('')}</div></section>`:button('完成練習，評估記憶','show-rating','','button primary full')}</article>`;
}
export function favoritesView(poems,state,kind) {
  const found=filterItems(kind==='quotes'?quoteEntries(poems).filter(q=>state.quotes.includes(q.id)):poems.filter(p=>state.progress[p.id]?.isFavorite),kind==='quotes'?'quote':'poem');
  return `<div class="page-heading"><p class="eyebrow">留一點喜歡，隨時重讀</p><h1>我的收藏</h1></div><div class="filters">${[['poems','我的詩詞'],['quotes','我的名句']].map(([id,label])=>button(label,'favorite-kind',`data-value="${id}" aria-pressed="${id===kind}"`,'chip'+(id===kind?' selected':''))).join('')}</div>${controls(found,kind==='quotes'?'quote':'poem')}${found.length?`<div class="poem-list">${found.map(item=>kind==='quotes'?`<div class="poem-row">${quoteTools(item)}<p class="poem-text" style="font-size:1.35rem">${e(item.text)}</p><p class="small muted">${e(item.poem.author)} · ${e(item.poem.title)}</p><div class="row between section">${item.lines?link('讀／背兩句',item.kind==='feihua'?`/feihua/${encodeURIComponent([...item.text].find(c=>/\p{Script=Han}/u.test(c)))}?line=${encodeURIComponent(item.id)}`:`/couplet/${item.id}`,'button text'):''}${link('讀全篇',`/read/${item.poem.id}`,'button text')}${button('取消收藏','quote-favorite',`data-id="${e(item.id)}"`,'button text')}</div></div>`:row(item)).join('')}</div>`:empty('這裡，留給你喜歡的詩','在詩詞或名句點下愛心，下次就能在這裡找到。')}`;
}
export function progressView(poems,state) {
  const learned=filterItems(poems.filter(p=>state.progress[p.id]?.reviewCount),'poem'),today=new Date().toLocaleDateString('zh-TW'),todayCount=state.events.filter(x=>new Date(x.date).toLocaleDateString('zh-TW')===today).length;
  return `<div class="page-heading"><p class="eyebrow">每一次重讀，都算數</p><h1>我的記憶足跡</h1></div><div class="stats-grid"><div class="stat"><strong>${learned.length}</strong><span>有練習紀錄</span></div><div class="stat"><strong>${state.events.length}</strong><span>累計複習</span></div><div class="stat"><strong>${todayCount}</strong><span>今天完成</span></div></div><p class="note">${poems.filter(p=>statusOf('poem',p.id)==='familiar').length} 首已很熟悉。學習記錄保存在這台裝置，可在設定匯出備份。</p><section class="section"><h2>下次再相遇</h2>${controls(learned,'poem')}<div class="poem-list section">${learned.map(p=>row(p,'practice',`上次練習：${RATINGS[state.progress[p.id].masteryLevel]} · ${dueLabel(state.progress[p.id].nextReviewDate)}`)).join('')}</div>${learned.length?'':empty('第一句，就是開始','完成一次背誦自評，就能留下你的記憶足跡。','/study')}</section>`;
}
export function settingsBody(state,voice,offline) {
  const s=state.settings;
  return `<section class="setting-group"><h3>讀得舒服</h3><h3>整體配色</h3><p class="small muted">選擇後立即套用到背景、卡片與導覽列。</p><div class="theme-grid">${Object.entries(THEMES).map(([id,name])=>button(`<span class="theme-preview" data-palette="${id}" aria-hidden="true"><i></i><i></i><i></i></span><span>${e(name)}</span>`,'theme',`data-value="${id}" aria-pressed="${id===s.theme}"`,'theme-option')).join('')}</div><label class="field"><span>正文大小</span><select data-setting="size">${[['small','小'],['medium','中'],['large','大'],['xl','特大']].map(([id,name])=>`<option value="${id}" ${id===s.size?'selected':''}>${name}</option>`).join('')}</select></label><label class="field"><span>生僻字顯示注音</span><input type="checkbox" data-setting="zhuyin" ${s.zhuyin?'checked':''}></label><label class="field"><span>朗讀速度</span><select data-setting="speed">${SPEEDS.map(n=>`<option value="${n}" ${n===s.speed?'selected':''}>${n}×</option>`).join('')}</select></label></section><section class="setting-group"><h3>中文朗讀</h3><p class="small muted">${voice?e(`${voice.name}（${voice.lang}）`):'尚未取得中文語音，請先在手機下載中文聲音。'}</p><p class="small muted">系統可能念錯古典多音字，以標示注音為準。飛航模式下是否能朗讀，需在你的 iPhone 實測。</p>${button(`${icon('play')}試聽一句`,'test-voice','','button soft section')}</section><section class="setting-group"><h3>保留學習記憶</h3><p class="small muted">記錄只在這台裝置，不會自動同步。清除網站資料或瀏覽器回收空間時可能遺失，請定期備份。</p><div class="row wrap section">${button(`${icon('download')}匯出背誦紀錄`,'export')}${button('匯入背誦紀錄','import')}</div><input type="file" id="backup-file" accept="application/json,.json" hidden></section><section class="setting-group"><h3>iPhone 使用方式</h3><p class="small muted">${offline==='ready'?'離線閱讀已準備完成。':'離線閱讀尚未準備完成。'}</p>${button(`${icon('phone')}安裝與驗證指引`,'install','','button soft section')}</section>`;
}
export function installBody(offline,error,state) {
  return `<section class="creator-signature"><strong>Vincent Chiou</strong><p>詩詞隨身背 · 製作於加拿大</p></section><div class="note">用 iPhone 的 Safari 開啟這個網址，即可開始。這是網頁 App，不需要 Mac、Xcode 或安裝原生開發工具。</div><ol class="steps"><li>在 Safari 開啟目前網址。若私人網站要求登入，使用建立此網站的同一個帳號。</li><li>點分享按鈕，再選「加入主畫面」。若有「作為網頁 App 開啟」，將它打開。</li><li>回到主畫面，點「詩詞隨身背」圖示。</li><li>保持連線直到下方顯示「離線閱讀已就緒」，再開飛航模式測試。</li></ol><div class="checklist section"><div class="check-row">${icon(offline==='ready'?'check':'cloud')}<div><strong>${offline==='ready'?'離線閱讀已就緒':'離線閱讀尚未就緒'}</strong><small>${offline==='ready'?'詩詞與操作介面已快取；仍請實際關網重開確認。':e(error||'需要 HTTPS 網址和瀏覽器快取支援，請保持連線。')}</small></div></div><div class="check-row">${icon('book')}<div><strong>501 首詩詞已載入</strong><small>先試搜尋「蘇軾」，再開啟《江城子》查看「鬢」的注音。</small></div></div><div class="check-row">${icon('heart')}<div><strong>確認學習資料有留下</strong><small>收藏一首詩、完成背誦自評，再關閉並重開，確認紀錄仍在。</small></div></div><div class="check-row">${icon('play')}<div><strong>朗讀要在手機實測</strong><small>先點下方試聽，再在飛航模式測試。瀏覽器聲音與背景播放可能受到系統限制。</small></div></div></div><div class="row wrap section">${button('重新準備離線','retry-offline','','button soft')}${button('試聽一句','test-voice')}${button('匯出備份','export')}</div><p class="small muted section">目前累計 ${state.events.length} 次複習。Windows 與 iPhone 的記錄各自保存，跨裝置請匯出後匯入。</p>`;
}

export {welcomeBanner} from './welcome-carousel.js';
